"""
HTTP 규칙 상수
"""

from http import HTTPStatus

# 2xx Success
HTTP_200_OK = HTTPStatus.OK
HTTP_201_CREATED = HTTPStatus.CREATED
HTTP_202_ACCEPTED = HTTPStatus.ACCEPTED
HTTP_204_NO_CONTENT = HTTPStatus.NO_CONTENT

# 3xx Redirect
HTTP_301_MOVED_PERMANENTLY = HTTPStatus.MOVED_PERMANENTLY
HTTP_302_FOUND = HTTPStatus.FOUND
HTTP_304_NOT_MODIFIED = HTTPStatus.NOT_MODIFIED

# 4xx Client Error
HTTP_400_BAD_REQUEST = HTTPStatus.BAD_REQUEST
HTTP_401_UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
HTTP_402_PAYMENT_REQUIRED = HTTPStatus.PAYMENT_REQUIRED
HTTP_403_FORBIDDEN = HTTPStatus.FORBIDDEN
HTTP_404_NOT_FOUND = HTTPStatus.NOT_FOUND
HTTP_405_METHOD_NOT_ALLOWED = HTTPStatus.METHOD_NOT_ALLOWED
HTTP_406_NOT_ACCEPTABLE = HTTPStatus.NOT_ACCEPTABLE
HTTP_408_REQUEST_TIMEOUT = HTTPStatus.REQUEST_TIMEOUT
HTTP_409_CONFLICT = HTTPStatus.CONFLICT
HTTP_410_GONE = HTTPStatus.GONE
HTTP_413_PAYLOAD_TOO_LARGE = HTTPStatus.REQUEST_ENTITY_TOO_LARGE
HTTP_415_UNSUPPORTED_MEDIA_TYPE = HTTPStatus.UNSUPPORTED_MEDIA_TYPE
HTTP_422_UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_ENTITY
HTTP_429_TOO_MANY_REQUESTS = HTTPStatus.TOO_MANY_REQUESTS

# 5xx Server Error
HTTP_500_INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
HTTP_501_NOT_IMPLEMENTED = HTTPStatus.NOT_IMPLEMENTED
HTTP_502_BAD_GATEWAY = HTTPStatus.BAD_GATEWAY
HTTP_503_SERVICE_UNAVAILABLE = HTTPStatus.SERVICE_UNAVAILABLE
HTTP_504_GATEWAY_TIMEOUT = HTTPStatus.GATEWAY_TIMEOUT

STATUS_TO_CODE = {s.value: s.name for s in HTTPStatus}
