"""
HTTP 규칙 상수
- 2xx: 성공
- 3xx: 리다이렉트
- 4xx: 클라이언트 에러
- 5xx: 서버 에러
"""

# 2xx Success
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_202_ACCEPTED = 202
HTTP_204_NO_CONTENT = 204

# 3xx Redirect
HTTP_301_MOVED_PERMANENTLY = 301
HTTP_302_FOUND = 302
HTTP_304_NOT_MODIFIED = 304

# 4xx Client Error
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_402_PAYMENT_REQUIRED = 402
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_405_METHOD_NOT_ALLOWED = 405
HTTP_406_NOT_ACCEPTABLE = 406
HTTP_408_REQUEST_TIMEOUT = 408
HTTP_409_CONFLICT = 409
HTTP_410_GONE = 410
HTTP_413_PAYLOAD_TOO_LARGE = 413
HTTP_415_UNSUPPORTED_MEDIA_TYPE = 415
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_429_TOO_MANY_REQUESTS = 429

# 5xx Server Error
HTTP_500_INTERNAL_SERVER_ERROR = 500
HTTP_501_NOT_IMPLEMENTED = 501
HTTP_502_BAD_GATEWAY = 502
HTTP_503_SERVICE_UNAVAILABLE = 503
HTTP_504_GATEWAY_TIMEOUT = 504

# Code (에러 응답 body의 code 필드)
BAD_REQUEST = "BAD_REQUEST"
UNAUTHORIZED = "UNAUTHORIZED"
PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
FORBIDDEN = "FORBIDDEN"
NOT_FOUND = "NOT_FOUND"
METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
NOT_ACCEPTABLE = "NOT_ACCEPTABLE"
REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
CONFLICT = "CONFLICT"
GONE = "GONE"
PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
VALIDATION_ERROR = "VALIDATION_ERROR"
TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
INTERNAL_ERROR = "INTERNAL_ERROR"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
BAD_GATEWAY = "BAD_GATEWAY"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"

STATUS_TO_CODE = {
    HTTP_400_BAD_REQUEST: BAD_REQUEST,
    HTTP_401_UNAUTHORIZED: UNAUTHORIZED,
    HTTP_402_PAYMENT_REQUIRED: PAYMENT_REQUIRED,
    HTTP_403_FORBIDDEN: FORBIDDEN,
    HTTP_404_NOT_FOUND: NOT_FOUND,
    HTTP_405_METHOD_NOT_ALLOWED: METHOD_NOT_ALLOWED,
    HTTP_406_NOT_ACCEPTABLE: NOT_ACCEPTABLE,
    HTTP_408_REQUEST_TIMEOUT: REQUEST_TIMEOUT,
    HTTP_409_CONFLICT: CONFLICT,
    HTTP_410_GONE: GONE,
    HTTP_413_PAYLOAD_TOO_LARGE: PAYLOAD_TOO_LARGE,
    HTTP_415_UNSUPPORTED_MEDIA_TYPE: UNSUPPORTED_MEDIA_TYPE,
    HTTP_422_UNPROCESSABLE_ENTITY: VALIDATION_ERROR,
    HTTP_429_TOO_MANY_REQUESTS: TOO_MANY_REQUESTS,
    HTTP_500_INTERNAL_SERVER_ERROR: INTERNAL_ERROR,
    HTTP_501_NOT_IMPLEMENTED: NOT_IMPLEMENTED,
    HTTP_502_BAD_GATEWAY: BAD_GATEWAY,
    HTTP_503_SERVICE_UNAVAILABLE: SERVICE_UNAVAILABLE,
    HTTP_504_GATEWAY_TIMEOUT: GATEWAY_TIMEOUT,
}
